maps/cs_xmas_italy.bsp
maps/cs_xmas_italy.res
gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
models/.mdl
models/chick.mdl
models/christmastree.mdl
models/feather.mdl
models/lethal/xms_hostie.mdl
models/lethal/xms_hostiegirl.mdl
models/smann.mdl
models/winebottle.mdl
sound/lethal/xmas/csign.wav
sound/lethal/xmas/deckhall.wav
sprites/flare1.spr
sprites/mc_lethal4.spr
sprites/star01.spr
